version: '3.1'

services:
  attacker:
    build: ./attack
    replicas: 2
    restart_policy:
      condition: on-failure
    resources:
      limits:
        cpus: "0.45"
        memory: 170M
    ports:
      - "22:22"
